import '../objects/meal.dart';

final List<Meal> meals = [
  Meal('Wypasik Cheese', [
    'bułka pasik',
    'majonez',
    'sałata lodowa',
    'mięso',
    'sos pomidor-bazylia',
    'cheddar',
    'majonez',
    'bułka pasik',
  ]),
  Meal('Wypasik Sweet Onion', [
    'bułka pasik',
    'majonez',
    'cebula duszona',
    'mięso',
    'cheddar',
    'sos BBQ',
    'bułka pasik',
  ]),
  Meal('Wypasik Classic', [
    'bułka pasik',
    'majonez',
    'sałata lodowa',
    'mięso',
    'ogórek kiszony',
    'biała cebula',
    'majonez',
    'bułka pasik',
  ]),
  Meal('Wypasik Jalapeno', [
    'bułka pasik',
    'sos majo-jalapeno',
    'sałata lodowa',
    'mięso',
    'jalapeno',
    'biała cebula',
    'sos majo-jalapeno',
    'bułka pasik',
  ]),
  Meal('Wypasik BBQ', [
    'bułka pasik',
    'majonez',
    'sałata lodowa',
    'mięso',
    'cheddar',
    'ogórek kiszony',
    'sos BBQ',
    'bułka pasik'
  ]),
  Meal('Sałatka Kurczak', [
    'sałata lodowa',
    'roszponka',
    'rukola',
    'sos ocet-oliwa',
    'pestki dyni',
    'pestki słonecznika',
    'pomidorki koktajlowe',
    'parmezan',
    'kurczak',
    'nachosy',
    'sos musztarda-miód-orzechy',
  ]),
  Meal('Sałatka Vege', [
    'sałata lodowa',
    'roszponka',
    'rukola',
    'sos ocet-oliwa',
    'pestki dyni',
    'pestki słonecznika',
    'pomidorki koktajlowe',
    'parmezan',
    'kurczak vege',
    'nachosy',
    'sos musztarda-miód-orzechy',
  ]),
  Meal('Gonzales', [
    'bułka',
    'sos różowy',
    'rukola',
    'mięso',
    'sos red hot',
    'cheddar',
    'jalapeno',
    'nachosy',
    'sos różowy',
    'bułka',
  ]),
  Meal('Awokadus', [
    'bułka',
    'sos różowy',
    'roszponka',
    'mięso',
    'guacamole',
    'sos musztarda-miód-orzechy',
    'cheddar',
    'boczek',
    'sos różowy',
    'bułka',
  ]),
  Meal('Standard', [
    'bułka',
    'sos biały',
    'sałata lodowa',
    'mięso',
    'cheddar',
    'pomidor',
    'ogórek kiszony',
    'biała cebula',
    'sos biały',
    'bułka',
  ]),
  Meal('Chorizard', [
    'bułka',
    'sos różowy',
    'rukola',
    'mięso',
    'pasta z suszonych pomidorów i żurawiny',
    'pieczarki',
    'cheddar',
    'chorizo',
    'sos różowy',
    'bułka',
  ]),
  Meal('Biały Wilk', [
    'bułka',
    'sos biały',
    'sałata lodowa',
    'mięso',
    'cebula duszona',
    'boczek',
    'boczek',
    'tymianek',
    'sos biały',
    'bułka',
  ]),
  Meal('Włoski Pastuch', [
    'bułka',
    'sos biały',
    'rukola',
    'parmezan',
    'mięso',
    'sos pomidor-bazylia',
    'boczek',
    'sos biały',
    'bułka',
  ]),
  Meal('Vegan Standard', [
    'bułka',
    'majonez vege',
    'sałata lodowa',
    'kotlet vege',
    'cheddar vege',
    'pomidor',
    'ogórek kiszony',
    'biała cebula',
    'majonez vege',
    'bułka',
  ]),
  Meal('Red Hot', [
    'bułka',
    'sos majo-jalapeno',
    'sałata lodowa',
    'mięso',
    'sos red hot',
    'świeże chili',
    'sos majo-jalapeno',
    'bułka',
  ]),
  Meal('Vegan Cebulion', [
    'bułka',
    'majonez vege',
    'rukola',
    'kotlet vege',
    'cebula duszona',
    'ogórek kiszony',
    'sos BBQ',
    'bułka',
  ]),
  Meal('Bebek Junior', [
    'bułka',
    'sos różowy',
    'sałata lodowa',
    'mięso',
    'sos BBQ',
    'cheddar',
    'boczek',
    'biała cebula',
    'sos różowy',
    'bułka',
  ]),
  Meal('Burger Miesiąca (Sierpień)', [
    'bułka',
    'majonez',
    'sałata rzymska',
    'mięso',
    'kimchi',
    'szczypiorek',
    'majonez',
    'bułka',
  ]),
  Meal('Burger Miesiąca (Wrzesień)', [
    'bułka',
    'sos majo-teriyaki',
    'roszponka',
    'mięso',
    'piklowany burak',
    'czerwona cebula',
    'ser feta',
    'sos majo-teriyaki',
    'bułka',
  ]),
  Meal('Stripsy', [
    'kawałek kurczaka',
    'kawałek kurczaka',
    'małe frytki',
    'sos różowy',
  ]),
  Meal('Polisz', [
    'bułka maślana',
    'sos biały',
    'sałata lodowa',
    'jajko sadzone',
    'boczek',
    'sos biały',
    'bułka maślana',
  ]),
  Meal('Świeżak', [
    'bułka maślana',
    'sos biały',
    'rukola',
    'jajko sadzone',
    'pomidor',
    'szczypiorek',
    'sos biały',
    'bułka maślana',
  ]),
  Meal('Boczuś', [
    'bułka maślana',
    'majonez',
    'pieczarki',
    'jajecznica',
    'cheddar',
    'boczek',
    'szczypiorek',
    'majonez',
    'bułka maślana',
  ]),
  Meal('Jajcarz', [
    'bułka maślana',
    'majonez',
    'pieczarki',
    'jajecznica',
    'cheddar',
    'szczypiorek',
    'majonez',
    'bułka maślana',
  ]),
  Meal('Wrap Standard', [
    'tortilla',
    'cheddar',
    'sos różowy',
    'kurczak',
    'sałata lodowa',
    'pomidor',
  ]),
  Meal('Wrap Bebek', [
    'tortilla',
    'cheddar',
    'sos BBQ',
    'kurczak',
    'cebula duszona',
    'ogórek kiszony',
  ]),
  Meal('Wrap Gonzo', [
    'tortilla',
    'cheddar',
    'sos majo-jalapeno',
    'kurczak',
    'pokruszone nachosy',
    'jalapeno',
    'biała cebula',
  ]),
];
